import ThePlatinum from '../assets/images/real-estates/ThePlatinum.jpg';
import CrystalJade from '../assets/images/real-estates/CrystalJade.jpg';
import Notara from '../assets/images/real-estates/Notara.jpg';
import TheImperial from '../assets/images/real-estates/TheImperial.jpg';
import CampusNest from '../assets/images/real-estates/CAMPUSNEST.jpg';
import GoldenUrban from '../assets/images/real-estates/GoldenUrban.png';
import TitaniumEstate from '../assets/images/real-estates/TitaniumEstate.jpg';
import EliteEstate from '../assets/images/real-estates/EliteEstate.png';
import DreamNest from '../assets/images/real-estates/DreamNest.png';
import EduNest from '../assets/images/real-estates/EduNest.jpg';
import CrownPalace from '../assets/images/real-estates/CrownPalace.png';

const Listings = [
        {
            id: 1,
            name: "The Platinum",
            image: ThePlatinum,
            location: "Agios Dimitrios, Athens, Greece",
            desc: "5-Star Service Apartments offer convenient rental options with luxurious, elegant designs that harmonize with the mild Mediterranean climate. Located in a prime area, these apartments provide comprehensive amenities that enhance the quality of life, ensuring an exceptional living experience.",
            sp1: "Blend of modern and classicBlend of modern and classic",
            sp2: "Large windows for natural light",
            sp3: "Luxurious and refined design",
            sp4: "Prime location in Agios Dimitrios near supermarkets and daily amenities",
            sp5: "Close to the Ellinikon mega-development, just 10 minutes by Metro",
            sp6: "Unique and charming cultural community",
            sp7: "Picturesque natural scenery",
            sp8: "",
            sp9: "",
            sp10: ""
        },
        {
            id: 2,
            name: "Crystal Jade",
            image: CrystalJade,
            location: "Drapetsona, Athens, Greece",
            desc: "With convenient transport links including buses, trains, marinas, and subways to famous sites and central Athens. Designed in Mediterranean style with A-class standards, it blends classic materials with modern architecture, offering elegant, nature-integrated living spaces with natural light. The project features a spacious rooftop, airy balconies, lush greenery, and luxurious European interiors for a refined living experience.",
            sp1: "Convenient transportation by bus, tram, metro, and cruise terminals",
            sp2: "Close to famous tourist attractions: Acropolis and Syntagma",
            sp3: "Class A design in Mediterranean style",
            sp4: "Spacious terrace and breezy balcony",
            sp5: "Luxurious European-standard interiors",
            sp6: "Strategic location with many surrounding amenities",
            sp7: "",
            sp8: "",
            sp9: "",
            sp10: ""
        },
        {
            id: 3,
            name: "Notara Elegant",
            image: Notara,
            location: "Piraeus, Athens, Greece",
            desc: "The project is surrounded by schools, hospitals, shopping centers, supermarkets, museums, and churches. Just a 3-minute walk to the beach, it features luxurious European interiors.",
            sp1: "300 meters from Piraeus port",
            sp2: "18 minutes to Syntagma Square",
            sp3: "Convenient transportation, near metro",
            sp4: "Just 3 minutes to Port Gate E9",
            sp5: "Easy access to ferries to famous islands",
            sp6: "Class A design, Mediterranean style",
            sp7: "Luxurious interiors, European quality",
            sp8: "Approximately 300 meters from the beach",
            sp9: "",
            sp10: ""
        },
        {
            id: 4,
            name: "The Imperial",
            image: TheImperial,
            location: "Dafni, Athens, Greece",
            desc: "Located in a strategic position that offers numerous living amenities. The area benefits from exceptionally convenient transportation infrastructure, providing easy access to landmarks, famous beaches, the airport, and entertainment venues.",
            sp1: "Only 6 minutes walk from Dafni Metro station",
            sp2: "Minimum investment of just 250,000 EUR",
            sp3: "Acropolis, Syntagma, Lycabettus: about a 10-minute drive",
            sp4: "Alimos, Glyfada, Asteras, Kalamaki beach: 12-20 minutes by car",
            sp5: "Near the luxurious Ellinikon mega-development: 5 metro stations",
            sp6: "Class A design, Mediterranean style",
            sp7: "Luxurious interiors, European quality",
            sp8: "Modern and elegant living space",
            sp9: "",
            sp10: ""
        },
        {
            id: 5,
            name: "Campus Nest",
            image: CampusNest,
            location: "Gerakas, Greece",
            desc: 'The 100% newly built project, "Campus Nest" serves as a perfect home or investment opportunity, providing convenient housing for families with children pursuing their education and offering stable, appreciating real estate value.',
            sp1: "Close to the famous Acropolis ancient site",
            sp2: "Well-developed transportation system",
            sp3: "Only 10-15 km to beautiful beaches",
            sp4: "Visit the vast Attica Zoo",
            sp5: "Just 9 minutes to the Metro station",
            sp6: "Amenities within a 2 to 4 minutes walk",
            sp7: "Easy access to the airport and universities",
            sp8: "Strategic area with diverse amenities",
            sp9: "Ideal and safe living environment",
            sp10: ""
        },
        {
            id: 6,
            name: "Golden Urban",
            image: GoldenUrban,
            location: "Piraeus, Athens, Greece",
            desc: "Located in Athens, Greece's economic and cultural hub, the site is near the world major Piraeus port and features a modern transportation system with Metro Line 3 connecting to the airport and landmarks. It hosts vibrant festivals and offers diverse amenities.",
            sp1: "Vibrant economic center of Athens",
            sp2: "Near the largest port in Europe, Piraeus",
            sp3: "Modern and convenient transportation",
            sp4: "Metro line 3 connects to the international airport",
            sp5: "Unique cultural festivals throughout the year",
            sp6: "Spacious living room with natural light",
            sp7: "3-bedroom apartments with high investment potential",
            sp8: "",
            sp9: "",
            sp10: ""
        },
        {
            id: 7,
            name: "Dream Nest",
            image: DreamNest,
            location: "Chalandri, Athens, Greece",
            desc: "Chalandri is a vibrant neighborhood, bustling with cocktail bars and cafés nestled along shaded pedestrian streets surrounding the St. Nicholas Church. It is also conveniently located near renowned universities and international schools, making it an ideal area for families seeking high-quality education for their children in Athens.",
            sp1: "Vibrant cusine center of Athens",
            sp2: "Near the largest port in Europe, Piraeus",
            sp3: "Modern and convenient transportation",
            sp4: "20 minutes to the Athens International Airport",
            sp5: "Unique cultural festivals throughout the year",
            sp6: "Spacious living room with natural light",
            sp7: "3-bedroom apartments with high investment potential",
            sp8: "Top medical services at Hygeia (400 m) and IASO hospital (1.2 km)",
            sp9: "A central hub for accessing international schools such as the American Community Schools (ACS) and the International School of Athens (ISA)",
            sp10: ""
        },
        {
            id: 8,
            name: "Edu Nest",
            image: EduNest,
            location: "Patision, Athens, Greece",
            desc: "Patision vibrant neighborhood boasts a lively atmosphere, featuring unique shops, charming cafés, and exceptional restaurants, ensuring a rich and diverse experience.",
            sp1: "Vibrant education center of Athens",
            sp2: "Near the largest port in Europe, Piraeus",
            sp3: "Modern and convenient transportation",
            sp4: "Metro line 1 and 2 (within 600 m)",
            sp5: "Numerous prestigious schools with EU-standard education, in less than 5 km radius",
            sp6: "Spacious rooms with natural light",
            sp7: "Surrounding area features numerous small parks, creating a balanced and harmonious living environment",
            sp8: "",
            sp9: "",
            sp10: ""
        },
        {
            id: 9,
            name: "Titanium Estate",
            image: TitaniumEstate,
            location: "Glyfada, Athens, Greece",
            desc: "Glyfada, known as the most affluent area in Athens, is home to intellectual elites, celebrities, and politicians of Greece. It symbolizes a luxurious lifestyle and offers immense investment potential.",
            sp1: "Vibrant political center of Athens",
            sp2: "With a sea view balconies, this project offers not only a premium living space, but also a serene and picturesque environment",
            sp3: "Luxury shopping centers, and fine dining establishments",
            sp4: "12 minutes from Glyfada Beach and Asteria Beach",
            sp5: "Located beside the ELLINKON Mega Urban Complex, the largest resort project in EU",
            sp6: "Glyfada Golf Club – One of Greece's largest and oldest golf courses, just 2 km away",
            sp7: "Ocean view to Glyfada Marina, elegance with sophisticated spaces, luxury yachts with views of the Mediterranean",
            sp8: "Apartments with ultra-wide balconies overlooking the Mediterranean Sea",
            sp9: "Private garden apartments offering a premium living experience with luxurious interiors",
            sp10: ""
        },
        {
            id: 10,
            name: "Elite Estate",
            image: EliteEstate,
            location: "Glyfada, Athens, Greece",
            desc: "Glyfada, known as the most affluent area in Athens, is home to intellectual elites, celebrities, and politicians of Greece. It symbolizes a luxurious lifestyle and offers immense investment potential.",
            sp1: "Vibrant political center of Athens",
            sp2: "With a sea view balconies, this project offers not only a premium living space, but also a serene and picturesque environment",
            sp3: "Luxury shopping centers, and fine dining establishments",
            sp4: "12 minutes from Glyfada Beach and Asteria Beach",
            sp5: "Located beside the ELLINKON Mega Urban Complex, the largest resort project in EU",
            sp6: "Glyfada Golf Club – One of Greece's largest and oldest golf courses, just 2 km away",
            sp7: "Ocean view to Glyfada Marina, elegance with sophisticated spaces, luxury yachts, with views of the Mediterranean",
            sp8: "Apartments with ultra-wide balconies overlooking the Mediterranean Sea",
            sp9: "",
            sp10: ""
        },
        {
            id: 11,
            name: "Crown Palace",
            image: CrownPalace,
            location: "Nikea, Athens, Greece",
            desc: "Life in Nikea is bustling, with lively streets and several thriving industrial areas. However, the area still maintains a sense of tranquility thanks to parks like Nikea Park, where residents can relax and enjoy the green spaces.",
            sp1: "Offering amenities for both residents and visitors, the area features restaurants, pharmacies, cinemas, and shopping centers",
            sp2: "Pharmacy 200 to 300 m",
            sp3: "Schools 550 m to 1.8 km",
            sp4: "Restaurants 40 m to 1.2 km",
            sp5: "Coffee and bars within radius of 300 m, nearest 10 m",
            sp6: "Metro radius within 280 m",
            sp7: "Supermarkets in range of 270 m radius",
            sp8: "Beaches within 4 km radius",
            sp9: "Spacious room designs with natural sunlight",
            sp10: "The shared garden area, with plenty of greenery, provides a perfect spot for relaxation and gatherings"
        }
    ]

export default Listings
